// flow-typed signature: f3442565b6da9a385153018d77c554f5
// flow-typed version: <<STUB>>/colors-regex_v^2.0.0/flow_v0.122.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'colors-regex'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'colors-regex' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'colors-regex/example' {
  declare module.exports: any;
}

declare module 'colors-regex/test' {
  declare module.exports: any;
}

// Filename aliases
declare module 'colors-regex/example.js' {
  declare module.exports: $Exports<'colors-regex/example'>;
}
declare module 'colors-regex/index' {
  declare module.exports: $Exports<'colors-regex'>;
}
declare module 'colors-regex/index.js' {
  declare module.exports: $Exports<'colors-regex'>;
}
declare module 'colors-regex/test.js' {
  declare module.exports: $Exports<'colors-regex/test'>;
}
